// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MapForms.Helpers;
//
//    var temperatures = Temperatures.FromJson(jsonString);

namespace MapForms.Helpers
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using System.IO;
    using System.Windows.Forms;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public class V2 { 
        public class Temperatures
        {
            [JsonProperty("type")]
            public string Type { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("crs")]
            public Crs Crs { get; set; }

            [JsonProperty("features")]
            public List<Feature> Features { get; set; }

            public static Temperatures FromJson(string fileName)
            {
                string path = Path.GetDirectoryName(Application.ExecutablePath) + $"\\DataSets\\{fileName}.json";
                if (File.Exists(path))
                {
                    string json = File.ReadAllText(path);
                    var obj = JsonConvert.DeserializeObject<Temperatures>(json, MapForms.Helpers.Converter.Settings);
                    return obj;
                }
                return null;
            }
        }

        public class Crs
        {
            [JsonProperty("type")]
            public string Type { get; set; }

            [JsonProperty("properties")]
            public CrsProperties Properties { get; set; }
        }

        public class CrsProperties
        {
            [JsonProperty("name")]
            public string Name { get; set; }
        }

        public class Feature
        {
            [JsonProperty("type")]
            public string Type { get; set; }

            [JsonProperty("properties")]
            public FeatureProperties Properties { get; set; }

            [JsonProperty("geometry")]
            public Geometry Geometry { get; set; }
        }

        public class Geometry
        {
            [JsonProperty("type")]
            public string Type { get; set; }

            [JsonProperty("coordinates")]
            public List<List<List<double>>> Coordinates { get; set; }
        }

        public class FeatureProperties
        {
            [JsonProperty("type")]
            public string Type { get; set; }
        }
    }

    public static partial class Serialize
    {
        public static string ToJson(this V2.Temperatures self) => JsonConvert.SerializeObject(self, MapForms.Helpers.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
